services:
  reactf:
    build:
      context: ./reactf
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - animeop-net
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - animeop-net
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
        - ./reactf/build:/usr/share/nginx/html  # Point NGINX to the React build directory
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reactf
      - api
    networks:
      - animeop-net
      


networks:
  animeop-net: